worker_processes auto;
worker_rlimit_nofile 100000;

events {
    worker_connections 4096;
    multi_accept on;
}

http {
    # Logging optimization untuk high load
    access_log off;
    error_log /var/log/nginx/error.log crit;

    # Tuning koneksi TCP mencegah bottleneck port exhaustion
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    keepalive_requests 1000;

    # LB terhubung ke instance 'api' via resolusi DNS container docker internal
    upstream flask_cluster {
        # Menggunakan IP resolusi internal service docker "api"
        # Kita tidak lagi butuh hardcoded IP public VM karena back-end ada dalam 1 VM
        least_conn;
        server api:5001;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://flask_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            
            # Waktu timeout yg lebih ketat untuk request stuck
            proxy_connect_timeout 5s;
            proxy_read_timeout 15s;
        }
    }
}